# .cpanel.yml - Example deployment script for a Laravel project

# Specify the build steps
deployment:
  tasks:
    - export DEPLOYPATH=/home/YOUR_C_PANEL_USERNAME/public_html
    - echo "Starting deployment..."

    # Step 1: Install Composer dependencies
    - echo "Installing composer dependencies..."
    - /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader

    # Step 2: Create/Update .env file (make sure .env is configured)
    - echo "Setting up .env file..."
    - cp .env.example .env || true
    - php artisan key:generate

    # Step 3: Run migrations
    - echo "Running migrations..."
    - php artisan migrate --force

    # Step 4: Clear and cache configurations
    - echo "Caching configurations..."
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache

    # Step 5: Link storage directory
    - echo "Linking storage directory..."
    - php artisan storage:link

    # Step 6: Set permissions for storage and bootstrap cache
    - echo "Setting correct permissions..."
    - find $DEPLOYPATH/storage -type d -exec chmod 775 {} \;
    - find $DEPLOYPATH/storage -type f -exec chmod 664 {} \;
    - find $DEPLOYPATH/bootstrap/cache -type d -exec chmod 775 {} \;
    - find $DEPLOYPATH/bootstrap/cache -type f -exec chmod 664 {} \;

    - echo "Deployment completed successfully!"
